import { Roboto_Condensed } from "next/font/google";
import "./globals.css";
import Provider from "@/lib/ThemeProvider/Provider";

const robotoCondensed = Roboto_Condensed({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={robotoCondensed.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
